### ISSUE TITLE
Snapshot does not including base bindings.

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/firely-net-sdk#1864] opened 2021-08-25 08:51 UTC
Hi,

We've encountered a subtle issue where Forge and Simplifier don't seem to play nice together (FHIR STU3). When we add the "11179-permitted-value-conceptmap"-extension to a binding in a profile, but don't alter the ValueSet that's being bound, Forge doesn't include the reference to the ValueSet in the differential. This seems fine since it's the same as the base from where the profile was derived from. 

However, when generating the snapshot the base bindings are not added even though they should be. 

For example, take the following snippet from our zib-AllergyIntolerance profile (https://simplifier.net/nictizstu3-zib2017/zib-allergyintolerance):
```
<binding>
<strength value="required" />
<valueSetReference>
<extension url="http://hl7.org/fhir/StructureDefinition/11179-permitted-value-conceptmap">
<valueReference>
<reference value="http://nictiz.nl/fhir/ConceptMap/AllergieStatusCodelijst-to-allergy-status" />
<display value="AllergieStatusCodelijst-to-allergy-status" />
</valueReference>
</extension>
<reference value="http://hl7.org/fhir/ValueSet/allergy-clinical-status"/>
</valueSetReference>
</binding>
```

Opening and saving this profile in Forge would remove the reference element from the differential as the "allergy-clinical-status" ValueSet is the same as in the core AllergyIntolerance resource.

**Comment by ewoutkramer** [comment] 2021-08-25 12:09
I think this is a duplicate of  #1516.  This has been fixed (it was a Firely Favorite) in the January 2021. Luckily, @mharthoorn is currently busy updating Simplifier to be able to use a newer version of the SDK.

**Comment by mmsmits** [comment] 2024-05-01 13:38
Assume this has been fixed

**Closed by mmsmits** 2024-05-01 13:38 UTC
Labels: awaiting response
