### ISSUE TITLE
Use new "HandleDuplicateProperties"

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1075] opened 2019-08-19 12:22 UTC
Newtonsoft has added settings to handle duplicate properties in Json - before it just hid the fact that duplicate properties existed at all.  We can now better validate the json - and (by use of a  setting?) trigger validation errors on encountering duplicate properties.

**Comment by mmsmits** [comment] 2024-02-14 14:09
duplicate of: https://github.com/FirelyTeam/firely-net-sdk/issues/1075

**Closed by mmsmits** 2024-02-14 14:09 UTC
Labels: enhancement
