### ISSUE TITLE
Reference/Assigner Validation fails without a non-null Reference field despite Cardinality and Explicit Rules in the Spec

### ISSUE THREAD

**Issue by blundstromcgi** [FirelyTeam/firely-net-sdk#2178] opened 2022-08-02 15:22 UTC
Fhirly SDK R4 4.1.0 (for Fhir 4.0.1, .NET 6.0):
using:
http://hl7.org/fhir/R4/definitions.json.zip

We have seem profile based validation working, but the documentation is lacking so I had to guess.

We keep getting one problem, an assigner, (assigner in any context as well, not sure about other references), which doesn’t have a reference field or it’s null, and just has the display field, Fhirly Validation fails on this rule with just the definitions from the Fhir spec above loaded:

ref-1 [Rule](https://www.hl7.org/fhir/R4/conformance-rules.html#rule)
(base) SHALL have a contained resource if a local reference is provided reference.startsWith('#').not() or (reference.substring(1).trace('url') in %rootResource.contained.id.trace('ids'))

But when we test against the public Fhirly Server, it doesn't fail.

Perhaps this is an issue with the documentation and not the SDK code, or a missing rule? FhirPath even works with our custom differential.

https://www.hl7.org/fhir/R4/references.html
The rule in Refence itself also seems confusing as the required fields At least one of reference, identifier and display SHALL be present (unless an extension is provided). (However, validation also failed when it only had an extension). So,our consensus was that only one should be required, at least in the context:

https://www.hl7.org/fhir/R4/datatypes-definitions.html#Identifier.assigner
The rule on assigner is written as:
Comments | The Identifier.assigner may omit the .reference element and only contain a .display element reflecting the name or other textual information about the assigning organization.

Regardless, the failure seems to contradict not only cardinality of the base Reference, but also the rules explicitly stated in assigner.

Wrong spec file? Need custom rules around textual rules that have no specific constraint generated into the spec? Bug?

JsonSerializerOptions PatientSerializationOptions = new JsonSerializerOptions().ForFhir(typeof(Patient).Assembly);

string validpatient = @"pathto/validpatient.json";
string zipsource = @"pathto/definitions.json.zip";
Patient p = null;
using (MemoryStream memory = new MemoryStream(File.ReadAllBytes(validpatient)))
{
    p = JsonSerializer.DeserializeAsync<Patient>(memory, PatientSerializationOptions).GetAwaiter().GetResult();
}

ZipSource resolver = new ZipSource(zipsource);

Hl7.Fhir.Validation.Validator validator = new Hl7.Fhir.Validation.Validator(
       new ValidationSettings()
       {
           ResourceResolver = resolver,
           GenerateSnapshot = true,
           ResolveExternalReferences = true
       });

var results = validator.Validate(p);
Valid Patient is

{
	"resourceType": "Patient",
	"id": "123",
	"text": {
		"status": "generated",
		"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Some narrative</div>"
	},
	"active": true,
	"name": [
		{
			"use": "official",
			"family": "Chalmers",
			"given": [
				"Peter",
				"James"
			]
		}
	],
	"identifier": [
		{
			"use": "official",
			"system": "http://some.system",
			"value": "123345654",
			"assigner": {
				"display": "Some Org"
			}
		}
	],
	"gender": "male",
	"birthDate": "1974-12-25",
	"meta": {
		"versionId": "7d510c1b-5f61-446f-abaf-c8ffcc34ff69",
		"lastUpdated": "2022-07-13T00:15:40.477+00:00"
	}
}

**Comment by ewoutkramer** [comment] 2022-08-02 15:51
You are not crazy, but you have hit a bug in the FHIR spec itself. If you are interested, you can see this is a *very* recent issue in the HL7 tracker: https://jira.hl7.org/browse/FHIR-37793?jql=project%3D%22FHIR%22%20AND%20text~%22ref-1%22

We are currently working on fixing this, and expect to post the update in our next (4.2) version.

**Comment by ewoutkramer** [comment] 2022-08-02 15:55
See https://github.com/FirelyTeam/firely-net-sdk/issues/2153 if you want to keep track of it!

**Comment by marcovisserFurore** [comment] 2022-08-11 08:29
Closed because duplicate of #2153

**Closed by marcovisserFurore** 2022-08-11 08:29 UTC
