### ISSUE TITLE
Downloaded JSON loses precision from uploaded XML

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/firely-net-sdk#1697] opened 2021-04-26 10:41 UTC
**Describe the bug**

Re: SIM-1609, uploading an XML file with
`<value value="10.10" />`
to Simplifier will lead to JSON representation (in both JSON tab and downloaded JSON file) of
`"value": 10.1,`

Which is a loss in precision which, as I understand [from the dragon in the spec](https://www.hl7.org/fhir/json.html#primitive), shouldn't happen.
See for example https://simplifier.net/snippet/wardweistra/27, which was created from XML input.

**To Reproduce**
1. Upload the XML from https://simplifier.net/snippet/wardweistra/27 to Simplifier.net (snippet or project).
2. Download the JSON
3. View the precision of the 'value'

**Expected behavior**
Precision is maintained as original 10.10

**Screenshots**
See https://simplifier.net/snippet/wardweistra/27

**Version used:**
 - FHIR Version: R4
 - Version: 1.9 (current Simplifier.net)

**Comment by mmsmits** [comment] 2024-03-28 09:52
Refinement:
We should create unit tests for both serializers to check whether this occurs, and why.

**Comment by Kasdejong** [comment] 2024-04-02 09:13
Hi @wardweistra, we tried to reproduce the issue in the SDK but failed to do so. This is our test:

```c#
[TestMethod]
      public void RetainsPrecision()
      {
          var xml = """
                    <Questionnaire xmlns="http://hl7.org/fhir">
                      <id value="3141"/>   
                      <url value="http://hl7.org/fhir/Questionnaire/3141"/>   
                      <name value="CancerQualityForumQuestionnaire2012"/>     
                      <status value="draft"/>
                      <item> 
                        <linkId value="1.1.1"/> 
                        <code> 
                          <system value="http://example.org/system/code/sections"/> 
                          <code value="CARDIAL"/> 
                        </code> 
                        <type value="group"/> 
                        <enableWhen> 
                          <question value="foo?"/>
                          <answerQuantity> 
                            <value value="1.10"/>
                            <system value="http://unitsofmeasure.org"/>
                            <code value="mm[Hg]"/>
                          </answerQuantity> 
                        </enableWhen> 
                      </item>
                    </Questionnaire> 
                    """;

          var node = FhirXmlNode.Parse(xml).ToTypedElement(ModelInspector.ForAssembly(typeof(TestQuestionnaire).Assembly));

          var json = node.ToJson(); // has correct precision

          var engine = FhirSerializationEngineFactory.Strict(ModelInspector.ForAssembly(typeof(TestQuestionnaire).Assembly));
          
          var poco = engine.DeserializeFromXml(xml);
          
          var json2 = engine.SerializeToJson(poco!); // has correct precision
      }
```

We need a few more details on how exactly the simplifier implementation works before we can more accurately test and fix this issue

**Comment by wardweistra** [comment] 2024-04-02 09:58
Thanks, will investigate our code and see if we can tell more about our implementation or if the error is in Simplifier code.

**Comment by PaulDeac** [comment] 2024-04-04 13:06
In Simplifier we are still using `Newtonsoft.Json`. We fixed it through a configuration setting:

```
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
    FloatParseHandling = FloatParseHandling.Decimal
};
```
We are planning to switch to `System.Text.Json` which is what I think the SDK is using, and that would also fix it. I think you can close this issue, the problem was in Simplifier.

**Closed** 2024-04-09 09:34 UTC
Labels: awaiting response, needs research
