### ISSUE TITLE
ResourceReference validation failing constraint ref-1 "SHALL have a contained resource if a local reference is provided" when using identifier reference

### ISSUE THREAD

**Issue by nico-ploner** [FirelyTeam/firely-net-sdk#2199] opened 2022-08-15 08:32 UTC
**Describe the bug**
When [referencing other resources](https://www.hl7.org/fhir/references.html) at least one of "reference", "identifier", or "display" shall be present. However, validating a resource containing a reference using an "identifier" rather than a "reference" fails giving the following error:

> Instance failed constraint ref-1 "SHALL have a contained resource if a local reference is provided"

**To Reproduce**
Create the following minimal QuestionnaireResponse resource referencing an external Patient resource providing answers.
```
var response = new QuestionnaireResponse
{
    Status = QuestionnaireResponse.QuestionnaireResponseStatus.Completed,
    Source = new ResourceReference
    {
        Type = "Patient",
        Identifier = new Identifier
        {
            System = "http://external.system/",
            Value = "1234"
        }
    }
};
```
Validate using the following snippet:
```
var resolver = new CachedResolver(
    new MultiResolver(
        ZipSource.CreateValidationSource(System.IO.Path.Combine(System.IO.Path.GetDirectoryName(typeof(Program).Assembly.Location), "specification.zip"))));
var validator = new Validator(new ValidationSettings
{
    ResourceResolver = resolver,
});
var outcome = validator.Validate(instance);
```

**Expected behavior**
Validation should pass constraint ref-1, since no local reference in property "reference" was provided.
The first part of the underlying expression `reference.startsWith('#').not()` should be satisfied when property "reference" is null or empty.

**Version used:**
 - FHIR Version: R4
 - Version: 4.1.0

**Additional context**
In comparison: the Java Validator implementation considers above QuestionnaireResponse resource valid.

Thank you in advance!

**Comment by nico-ploner** [comment] 2022-08-15 08:37
I just checked #2186 and found this very issue already addressed there, thus only adding that references with only an identifier should also succeed.

**Comment by marcovisserFurore** [comment] 2022-08-15 08:37
Thanks @nico-ploner for your issue. In the next release this will be solved by changing the expression of `ref-1` to:

```
"reference.exists() implies (reference.startsWith('#').not() or (reference.substring(1).trace('url') in %rootResource.contained.id.trace('ids')) or (reference='#' and %rootResource!=%resource))
```

The next release (4.2.0) will be rolled out this week.

**Comment by nico-ploner** [comment] 2022-08-15 08:38
Thank you @marcovisserFurore for your quick reply.

**Comment by marcovisserFurore** [comment] 2022-08-15 08:40
Closing this issue because duplicate of #2153.

**Closed by marcovisserFurore** 2022-08-15 08:40 UTC
