### ISSUE TITLE
HAPI-0365 Error Message while creating Patient

### ISSUE THREAD

**Issue by parthakbari** [FirelyTeam/firely-net-sdk#2160] opened 2022-07-21 12:52 UTC
Hi Team,

I am new in hapi-Fhir and try to understand this concept. During POC implementation, Getting below error while creating Patient.

**Error message :** `Hl7.Fhir.Rest.FhirOperationException: 'Operation was unsuccessful because of a client error (BadRequest). OperationOutcome: <div xmlns="http://www.w3.org/1999/xhtml"><h1>Operation Outcome</h1><table border="0"><tr><td style="font-weight: bold;">ERROR</td><td>[]</td><td><pre>HAPI-0365: Can not create resource with ID &quot;Patient&quot;, ID must not be supplied on a create (POST) operation (use an HTTP PUT / update operation if you wish to supply an ID)</pre></td>`

**Sample Code**
            
    var client = new FhirClient("http://hapi.fhir.org/baseR4/Patient/");
    
    client.Settings.PreferredFormat = ResourceFormat.Json;
    client.Settings.UseFormatParameter = true;
    client.Settings.PreferredReturn = Prefer.ReturnMinimal;
    client.Timeout = 120000;
    
    var pat = new Patient();
    
    var id = new Identifier();
    id.System = "http://hl7.org/fhir/sid/us-ssn";
    id.Value = "000-12-3456";
    pat.Identifier.Add(id);
    
    var name = new HumanName().WithGiven("Christopher").WithGiven("C.H.").AndFamily("Parks");
    name.Prefix = new string[] { "Mr." };
    name.Use = HumanName.NameUse.Official;
    
    var nickname = new HumanName();
    nickname.Use = HumanName.NameUse.Nickname;
    nickname.GivenElement.Add(new FhirString("Chris"));
    
    pat.Name.Add(name);
    pat.Name.Add(nickname);
    
    pat.Gender = AdministrativeGender.Male;
    
    pat.BirthDate = "1983-04-23";
    
    var birthplace = new Extension();
    birthplace.Url = "http://hl7.org/fhir/StructureDefinition/birthPlace";
    birthplace.Value = new Address() { City = "Seattle" };
    pat.Extension.Add(birthplace);
    
    var birthtime = new Extension("http://hl7.org/fhir/StructureDefinition/patient-birthTime",
                                   new FhirDateTime(1983, 4, 23, 7, 44));
    pat.BirthDateElement.Extension.Add(birthtime);
    
    var address = new Address()
    {
        Line = new string[] { "3300 Washtenaw Avenue, Suite 227" },
        City = "Ann Arbor",
        State = "MI",
        PostalCode = "48104",
        Country = "USA"
    };
    pat.Address.Add(address);
    
    var contact = new Patient.ContactComponent();
    contact.Name = new HumanName();
    contact.Name.Given = new string[] { "Susan" };
    contact.Name.Family = "Parks";
    contact.Gender = AdministrativeGender.Female;
    contact.Relationship.Add(new CodeableConcept("http://hl7.org/fhir/v2/0131", "N"));
    contact.Telecom.Add(new ContactPoint(ContactPoint.ContactPointSystem.Phone, null, ""));
    pat.Contact.Add(contact);
    
    pat.Deceased = new FhirBoolean(false);
    
    //client.Operation 
    var created_pat = client.Create<Patient>(pat);`

Source :  https://docs.fire.ly/projects/Firely-NET-SDK/model/patient-example.html
Package version : Hl7.Fhir.R4 (3.8.3) or Hl7.Fhir.STU3 (3.8.3)

Tried with both standard one by one but getting same error.

Please support.

**Comment by marcovisserFurore** [comment] 2022-07-21 13:53
Hi @parthakbari , thanks for your question.

First of all, you are using an incorrect extension for `birthPlace`. That uri should be `http://hl7.org/fhir/StructureDefinition/patient-birthPlace`. 

Then I tried to reproduce this on my system and I get the same error. However, when I post it to our Firely Server (https://server.fire.ly/R4) everything works fine. 

When I post the json of your Patient resource in Postman to http://hapi.fhir.org/baseR4/Patient/ I got the same result:

```json
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>HAPI-0365: Can not create resource with ID &quot;Patient&quot;, ID must not be supplied on a create (POST) operation (use an HTTP PUT / update operation if you wish to supply an ID)</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-0365: Can not create resource with ID \"Patient\", ID must not be supplied on a create (POST) operation (use an HTTP PUT / update operation if you wish to supply an ID)"
        }
    ]
}
```

So there is something wrong with the Hapi server. Maybe you can contact them?

Btw, your resource in Json looks like this:
```json
{
   "resourceType":"Patient",
   "extension":[
      {
         "url":"http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
         "valueAddress":{
            "city":"Seattle"
         }
      },
      {
         "url":"http://hl7.org/fhir/StructureDefinition/patient-birthTime",
         "valueDateTime":"1983-04-23T07:44:00+02:00"
      }
   ],
   "identifier":[
      {
         "system":"http://hl7.org/fhir/sid/us-ssn",
         "value":"000-12-3456"
      }
   ],
   "name":[
      {
         "use":"official",
         "family":"Parks",
         "given":[
            "Christopher",
            "C.H."
         ],
         "prefix":[
            "Mr."
         ]
      },
      {
         "use":"nickname",
         "given":[
            "Chris"
         ]
      }
   ],
   "gender":"male",
   "birthDate":"1983-04-23",
   "deceasedBoolean":false,
   "address":[
      {
         "line":[
            "3300 Washtenaw Avenue, Suite 227"
         ],
         "city":"Ann Arbor",
         "state":"MI",
         "postalCode":"48104",
         "country":"USA"
      }
   ],
   "contact":[
      {
         "relationship":[
            {
               "coding":[
                  {
                     "system":"http://hl7.org/fhir/v2/0131",
                     "code":"N"
                  }
               ]
            }
         ],
         "name":{
            "family":"Parks",
            "given":[
               "Susan"
            ]
         },
         "telecom":[
            {
               "system":"phone",
               "value":""
            }
         ],
         "gender":"female"
      }
   ]
}
```

**Comment by marcovisserFurore** [comment] 2022-07-26 09:09
I performed the test again, and now it works in Postman and in the Firely .NET SDK with the Hapi server. Perhaps there was a glitch in their system. Therefore I am closing this issue.

**Closed by marcovisserFurore** 2022-07-26 09:09 UTC
