### ISSUE TITLE
Add support for adding (and subtracting) date quantities from dates

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2675] opened 2024-01-22 10:33 UTC
(see https://github.com/FirelyTeam/firely-net-sdk/issues/2431#issuecomment-1744681689)

I would like to add to this that executing the examples in https://hl7.org/fhirpath/N1/#subtraction-2, also provides an error in the [FHIRPath playground](https://simplifier.net/fhirpath?filepath=package/CapabilityStatement-base.json&scope=hl7.fhir.r4.core@4.0.1&query=%402019-03-01%20-%2024%20months).

This can be worked around by [adding a '+' to the fhirpath](https://simplifier.net/fhirpath?filepath=package/CapabilityStatement-base.json&scope=hl7.fhir.r4.core@4.0.1&query=%402019-03-01%20%2B%20-24%20months).

**Comment by mmsmits** [comment] 2024-03-27 09:23
duplicate of [#2691](https://github.com/FirelyTeam/firely-net-sdk/issues/2691)

**Closed by mmsmits** 2024-03-27 09:23 UTC
Labels: enhancement
