### ISSUE TITLE
Validation not ending

### ISSUE THREAD

**Issue by cknaap** [FirelyTeam/firely-net-sdk#702] opened 2018-09-20 14:37 UTC
[Avery919_Simonis280_ec19aa26-469a-41d6-be66-c09df4adb0c5.zip](https://github.com/ewoutkramer/fhir-net-api/files/2401738/Avery919_Simonis280_ec19aa26-469a-41d6-be66-c09df4adb0c5.zip)

If you load the profiles from StandardHealthRecord (https://simplifier.net/StandardHealthRecord), and validate this Synthea generated Bundle as a whole, Validator seems to go in a loop.

Observed this when trying it on vonk, POST {url}/Bundle/$validate. The validator kept resolving the same set of profiles over and over again. I forcibly stopped it after 500K resolve actions.

When I tried with only the first 3 entries in the bundle, the validator did succeed.

**Comment by ewoutkramer** [comment] 2018-09-20 15:55
Well, there still is no loopdetection, so if in the instance there is a loop of resources referencing each other, the validation will not end. So, that's probably the cause!

**Comment by ewoutkramer** [comment] 2018-09-26 10:18
So: let's turn this into an action: need to add loop detection to the validator.

**Comment by wmrutten** [comment] 2018-10-30 09:50
The SnapshotGenerator also requires cycle detection to prevent endless loops / deadlocks.
Currently, SSGen class contains internal cycle detection logic. Been pondering about moving cycle detection logic into a separate (re-usable, composable) CycleDetectionResourceResolver wrapper.
Maybe Validator could also benefit from same approach?

**Comment by brianpos** [comment] 2021-03-11 21:55
I have also ran into this one now, and came up with a few use cases that cause it.
And also some logic that I now run in my server to catch it/cleanse it before passing it into the validator.
```
            var allRes = r.AllResources();
            allRes.Insert(0, r);
            foreach (var item in allRes)
            {
                System.Diagnostics.Trace.WriteLine($"{item.TypeName}/{item.Id}");
                // Check if this item has references to itself.
                var myRefs = item.AllReferences();
                var selfReferences = myRefs.Where(mr => mr.Reference == $"#{item.Id}");
                if (selfReferences.Any())
                {
                    System.Diagnostics.Trace.WriteLine($"** Cycle detected: {item.TypeName}/{item.Id}");
                    foreach (var updateRef in selfReferences)
                    {
                        // if (updateRef.Reference == "#")
                            updateRef.Reference = "#LOOP_DETECTED";
                    }
                }
            }
```
Where the 2 extension methods scan down the resource (using the ClassMappings) to find resource instances, and resource references.

The 2 specific cases that I found were validating a new resource (with no Id included) and a property in the resource like this
```
<basedOn>
	<reference value="#" />
</basedOn>
```
And the other is where a contained resource has a reference to itself.

**Comment by brianpos** [comment] 2021-03-11 21:58
@cknaap did you get this resolved in the Vonk server?

**Comment by marcovisserFurore** [comment] 2021-09-02 08:43
This issue has been marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

Will also be solved in the new Validator.

**Closed by marcovisserFurore** 2021-09-02 08:43 UTC
Labels: enhancement, [Validator]
