### ISSUE TITLE
Some help about RESTFul service

### ISSUE THREAD

**Issue by testlorenzospa** [FirelyTeam/firely-net-sdk#2505] opened 2023-06-16 15:24 UTC
Hello.

I want to use this library to read a FHIR bundle in JSON from a RESTFul service.
However, I haven't a connection to use for this.
Can I read a fixed JSON string to verify how this library work? If yes, there is some example?

Let me know, please.

Thanks.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version used:**
 - FHIR Version: [e.g. STU3, R4, R5]
 - Version: [e.g. 1.9.0]

**Additional context**

**Comment by mbaltus** [comment] 2023-06-16 19:13
Duplicate of #2503. Not an issue, but a question, so decided to close this one.

**Closed by mbaltus** 2023-06-16 19:13 UTC
