### ISSUE TITLE
Trailing new-lines from properties being removed when deserializing the raw JSON API response into the Resource/POCO

### ISSUE THREAD

**Issue by RandolphBurt** [FirelyTeam/firely-net-sdk#2672] opened 2024-01-17 12:16 UTC
**Describe the bug**

We are using .net and the Firely nuget. We have updated from the 0.96 version of the Firely Nuget package to the latest (5.4.0). As a result we've found, when reading a resource from a third party, that Firely removes all newlines from the end of the resource properties. This behaviour was not present in the old 0.96 version.

**To Reproduce**
1. Use the FhirClient to read a resource (e.g. by calling `fhirClient.Read($"Appointment/{appointmentId}"`) where the appointment resource contains a Comment property with a newline at the end

**Expected behavior**
When reading a resource - e.g. by calling `fhirClient.Read($"Appointment/{appointmentId}"` we would expect the resource properties to contain the **exact** value as held in the raw JSON data. No trailing new lines should be removed.

**Screenshots**
The below screenshot is from Visual Studio where I have a break-point after the API call. It shows two orange circles. The top one shows the content of the Comment property in the Resource/POCO, which has no trailing new line. The second circle shows the raw json with the trailing new line.

![image](https://github.com/FirelyTeam/firely-net-sdk/assets/1282232/f4826387-e304-4401-b862-b018355153ab)

**Version used:**
 - FHIR Version: R4
 - Version: 5.4.0

**Additional context**
The reason this is a problem for us....
In one particular implementation we read an appointment (by calling fhirClient.Read($"Appointment/{appointmentId}") and receive an Appointment resource which contains a Comment property with a newline at the end. I can see in the raw JSON response the newline is present, however the Appointment Resource/POCO given to us in code by Firely has the newline removed from the end of the Comment property.
This presents a problem for us with a particular integration when cancelling appointments. The integration specification states we should read the appointment, update it's Status to 'cancelled' and then send it back. The third party system will then validate our cancellation request, however they are rejecting our cancellation because it's not just the Status that has changed on the Appointment - The comment has changed as well - the trailing new line has been removed. Ideally the third party would not be so picky, however they are conforming to the specification. And to be fair we want the POCO to contain **exactly** what was present in the raw JSON anyway.

I did search the Firely github code and found this... https://github.com/FirelyTeam/firely-net-sdk/blob/98d7fbe718d4c1faa6e4e45d7e0d5d9b2f513ccd/src/Hl7.Fhir.Base/Serialization/FhirJsonNode.cs#L185
It sounds like it is trimming JSON text to be compatible with the xml serializer, so maybe that is the code that is the problem – and if so then possibly on purpose? If this is therefore by design and not a bug, can we have a configuration option to NOT remove these trailing new lines?

![image](https://github.com/FirelyTeam/firely-net-sdk/assets/1282232/ff70aae8-29da-4d5b-8940-7bd0ac63d2c7)

**Comment by ewoutkramer** [comment] 2024-01-17 12:38
Possible duplicate of #2661.

This is fixed in the new serializers/deserializers!  We're leaving the original serializers untouched, since the behaviour has been around for quite long (a lot has happened since 0.96 ;-)), so we're trusting on the new serializers (which are more speedy too) to solve this.

See https://docs.fire.ly/projects/Firely-NET-SDK/en/latest/parsing/system-text-json-serialization.html for more info!

**Comment by RandolphBurt** [comment] 2024-01-17 15:30
Many thanks for your quick reply.
How do I 'plug this in' / 'turn this on' for use with the FhirClient.  e.g. calling `FhirClient.Read($"Appointment/{appointmentId}")` 
I'm not explicitly serializing/deserializing the JSON myself with the serializers. I'm just using the FhirClient to call an endpoint. Do I need to set something on the FhirClientSettings to tell it to use the new serializers?

**Comment by ewoutkramer** [comment] 2024-01-19 17:12
See #2661. I am closing this issue to avoid duplicating discussions ;-)

**Closed by ewoutkramer** 2024-01-19 17:12 UTC
