### ISSUE TITLE
Look at "formalized" return codes from terminology services

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2685] opened 2024-01-29 12:49 UTC
At the Jan 2024 WGM Grahame spoke about how he had sat down with Michael Lawley and worked on testcases for terminology services to nail down the appropriate HTTP result codes for each operation and warning/error. This has been codified into tests for the validator.

Grahame said he would also extract these codes and bring them back to the spec, but until that time, we should look at the tests and find which http result codes to expect.

**Comment by mmsmits** [comment] 2024-05-01 13:49
Duplicate of #2263

**Closed by mmsmits** 2024-05-01 13:49 UTC
Labels: enhancement
