### ISSUE TITLE
line numbering in the json parser is not correct

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#1078] opened 2019-08-22 05:39 UTC
Having just added position info to the FhirPathTester to be able to indicate the node that you have selected, the XML line numbering works great, however the Json line numbering isn't accurate.
Will come up with a unit test at some stage.

**Comment by ewoutkramer** [comment] 2019-08-22 10:08
Is it never accurate, or just sometimes?

**Comment by brianpos** [comment] 2019-08-22 10:42
Haven't seen it right yet, but only tried a little.
I normally use the xml. 
I'll try it out on more resource examples to find out

**Comment by ewoutkramer** [comment] 2019-09-24 14:19
Any progress, @brianpos?

**Comment by gstoian** [comment] 2019-11-14 12:05
Hey @brianpos ! I did some tests and I couldn't reproduce the issue. The only thing I found is that it might get a bit confusing when you are navigating through an element's children and one of the children is actually an array. Then you will have each element of the array as individual child in the result and the LineNumber (of the child) will point to that exact location of `{`.

**Comment by brianpos** [comment] 2019-11-14 12:07
I'll do more research on it.
It's a feature in the UWP fhirpath tester, I'll do more playing in there.

**Comment by marcovisserFurore** [comment] 2020-02-24 09:18
We cannot reproduce this issue.

**Comment by brianpos** [comment] 2020-09-04 02:48
I ended up creating a unit test that demonstrates this issue quite nicely, and shows that it works perfectly with XML
```
    [TestClass]
    public class ParserLineNumberingTest
    {
        [TestMethod]
        public void CheckJsonLineNumbering()
        {
            var json = "{ \"resourceType\": \"Patient\",  \"name\": [ { \"family\": \"pos\", \"given\": [ \"brian\",  \"richard\" ] } ], \"birthDate\": \"1980\" }";
            var node = Hl7.Fhir.Serialization.FhirJsonNode.Parse(json);
            int lastPos = 0;
            IPositionInfo lastNode = null;
            System.Diagnostics.Trace.WriteLine(json);
            AddLocations(node, ref lastNode, ref lastPos, json.ToCharArray());
        }

        [TestMethod]
        public void CheckXmlLineNumbering()
        {
            var xml = "<Patient xmlns=\"http://hl7.org/fhir\"><name><family value=\"pos\"/><given value=\"brian\"/><given value=\"richard\"/></name><birthDate value=\"1980\"/></Patient>";
            var node = Hl7.Fhir.Serialization.FhirXmlNode.Parse(xml);
            int lastPos = 0;
            IPositionInfo lastNode = null;
            System.Diagnostics.Trace.WriteLine(xml);
            AddLocations(node, ref lastNode, ref lastPos, xml.ToCharArray());
        }

        private void AddLocations(ISourceNode node, ref IPositionInfo lastNode, ref int lastCharPos, char[] chars)
        {
            int location = 0;
            IPositionInfo posInfo = node.Annotation<Hl7.Fhir.Serialization.XmlSerializationDetails>();
            if (posInfo == null)
                posInfo = node.Annotation<Hl7.Fhir.Serialization.JsonSerializationDetails>();
            if (posInfo != null)
            {
                if (lastNode == null)
                    location = 0;
                else
                {
                    var linesToSkip = posInfo.LineNumber - lastNode.LineNumber;
                    var colsToSkip = posInfo.LinePosition;
                    if (linesToSkip == 0)
                        colsToSkip -= lastNode.LinePosition;
                    while (linesToSkip > 0 && lastCharPos < chars.Length)
                    {
                        lastCharPos++;
                        if (chars[lastCharPos] == '\r')
                            linesToSkip--;
                    }
                    lastCharPos += colsToSkip;
                    location = lastCharPos; // need to patch this
                }
                lastNode = posInfo;
                System.Diagnostics.Trace.WriteLine($"{location}: {node.Location}");
                for (int n = 0; n < location; n++)
                    System.Diagnostics.Trace.Write("-");
                System.Diagnostics.Trace.WriteLine("^");
            }
            lastCharPos = location;
            foreach (var child in node.Children())
            {
                AddLocations(child, ref lastNode, ref lastCharPos, chars);
            }
        }
    }
```

This outputs the following results
```
Debug Trace:
{ "resourceType": "Patient",  "name": [ { "family": "pos", "given": [ "brian",  "richard" ] } ], "birthDate": "1980" }
0: Patient
^
40: Patient.name[0]
----------------------------------------^
56: Patient.name[0].family[0]
--------------------------------------------------------^
76: Patient.name[0].given[0]
----------------------------------------------------------------------------^
88: Patient.name[0].given[1]
----------------------------------------------------------------------------------------^
115: Patient.birthDate[0]
-------------------------------------------------------------------------------------------------------------------^

Debug Trace:
<Patient xmlns="http://hl7.org/fhir"><name><family value="pos"/><given value="brian"/><given value="richard"/></name><birthDate value="1980"/></Patient>
0: Patient
^
37: Patient.name[0]
-------------------------------------^
43: Patient.name[0].family[0]
-------------------------------------------^
64: Patient.name[0].given[0]
----------------------------------------------------------------^
86: Patient.name[0].given[1]
--------------------------------------------------------------------------------------^
117: Patient.birthDate[0]
---------------------------------------------------------------------------------------------------------------------^
```

**Comment by brianpos** [comment] 2020-09-07 19:57
I think that it is more that it is inconsistent, and not clear what IS being selected.
For XML it points to the start of the xml element, for json it is at the value (maybe)

**Comment by mmsmits** [comment] 2021-06-03 14:02
Hi @brianpos, from your unit test it seems that in Json it points to the end of a primitive value (string) or the beginning of an object.
These positioning numbers aren't being calculated by the SDK, but come straight from Newtonsoft. See here: 
https://github.com/FirelyTeam/firely-net-common/blob/8e4e533e04a63e9183a5924c723f5fa18d1ea78e/src/Hl7.Fhir.Serialization/FhirJsonNode.cs#L314

**Comment by ewoutkramer** [comment] 2021-06-03 14:23
I found it hard to believe, so I tried something *really* simple:

``` csharp
var jo = JObject.Parse("{ \"arend\" : 4, \"berend\" : \"botje\" }");
var a = jo["arend"] as IJsonLineInfo;
var pos = a.LinePosition;
```

Guess what `pos` is?  13!  So the lineinfo for the json property `arend` actually points to the end of the property....

**Comment by mmsmits** [comment] 2021-06-03 14:26
Thanks for double checking @ewoutkramer 
I'll close it for now.

**Closed by mmsmits** 2021-06-03 14:26 UTC
Labels: bug

**Comment by ewoutkramer** [comment] 2021-06-03 14:28
I tried to get the position of the first property, just to make sure:

``` csharp
var jo = JObject.Parse("{ \"arend\" : 4, \"berend\" : \"botje\" }");
var a = jo.Properties().First();
var pos = ((a) as IJsonLineInfo).LinePosition;
```

This will return 11 - so just after the key of the property.
