### ISSUE TITLE
Swagger doesn't work with after updating R4

### ISSUE THREAD

**Issue by VladislavAntonyuk** [FirelyTeam/firely-net-sdk#2103] opened 2022-05-26 12:43 UTC
**Describe the bug**
Swashbuckle.AspNetCore doesn't generate schema after updating Hl7.Fhir.R4 from version 3.8.3 to 4.0.0

**To Reproduce**
1. Create new AspNetCore WebApi project
2. Add "Swashbuckle.AspNetCore 6.3.1
3. Add CRUD operations to the controller
4. Install Hl7.Fhir.R4 version 3.8.3
5. Run - it should display schema
6. Update Hl7 package to v4.0.0
7. Run - schema is not displayed

**Expected behavior**
Swagger schema is displayed

**Screenshots**

**Version used:**
 - FHIR Version: R4
 - Version: 4.0.0

**Additional context**

**Comment by ewoutkramer** [comment] 2022-05-30 08:37
I never use Swashbuckle, I didn't even know it worked in the first place ;-)  Honestly, I know nothing about it, so if you can find out what's wrong that would be really helpful.

**Comment by VladislavAntonyuk** [comment] 2022-05-30 19:39
do you need a small repro link to reproduce it?

**Comment by ewoutkramer** [comment] 2022-05-30 21:00
Well, I know nothing about Swashbuckle, so I would not be able to diagnose it. I need someone else to fix this.

**Comment by brianpos** [comment] 2022-05-31 03:19
If you provide the small repo I can take a look at it.

**Comment by VladislavAntonyuk** [comment] 2022-06-06 08:42
3.8.3
![image](https://user-images.githubusercontent.com/33021114/172126457-60d7ca65-815d-40cd-a30a-e42d0bd6fe75.png)
4.0.0
![image](https://user-images.githubusercontent.com/33021114/172126559-0fcf8a7a-3a66-4426-bd43-180eefda7290.png)
Sample
[Sample.zip](https://github.com/FirelyTeam/firely-net-sdk/files/8843044/Sample.zip)

**Comment by almostchristian** [comment] 2022-06-13 02:16
I encountered this same error in my code. The root cause of your error is because the Base type implements IReadOnlyDictionary and IEnumerable starting in 4.0.0, which is given special handling by the default schema generator in Swashbuckle before attempting to read its properties.

I solved this by adding a custom ISerializerDataContractResolver to the service collection which bypasses the issue found in the default resolver. You can basically copy the [existing schema generator](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs), omitting the parts that does the special processing if the object is a IDictionary or an IEnumerable.

**Comment by almostchristian** [comment] 2022-06-13 13:36
I'm not sure how to resolve this without rewriting Base to not implement IReadOnlyDictionary and IEnumerable. The other option would be to enhance Swashbuckle to allow it to ignore of the type implements those interfaces.

However, I found that if you want to use Swashbuckle to generate documentation for your API, you need to have a custom ISerializerDataContractResolver. The custom resolver I have in my project not only fixes the issue raised here, but it also is able to rewrite the choice properties, as well as use the correct enum values, instead of just the plan ToString() used by the built-in data contract resolver.

Below is a sample of the swagger documentation generated in our project using a custom ISerializerDataContractResolver.
![image](https://user-images.githubusercontent.com/2035340/173365508-ae103a42-12fe-497d-9bdb-34ad3286cff5.png)

**Comment by mmsmits** [comment] 2022-06-13 13:44
Thanks @almostchristian for your elaborate feedback! We don't use Swashbuckle ourselves, so this really helps.

@VladislavAntonyuk  From @almostchristian 's answers, it doesn't look like this is something we can help with, but either an issue for Swashbuckle or something you need to write your own ISerializerDataContractResolver for.

I'm closing this issue for now. Please reopen it, when you think we can make your life easier (we will not stop implementing  IReadOnlyDictionary and IEnumerable in the near future ;) )

**Closed by mmsmits** 2022-06-13 13:44 UTC
Labels: awaiting response

**Comment by brianpos** [comment] 2022-06-13 23:46
I'll see if there is something that we can include to make this process/configuration easier. (But agree that we won't be changing the Base etc)

**Comment by almostchristian** [comment] 2022-06-14 03:21
It's based on the resolver from the Swashbuckle repo, but I added enhancements to handle the choice types, using the enum values from the EnumUtility, and directly mapping the primitive types. I also made it so that the Extension property is hidden from types other than the DomainResource to simplify the generated schema.

```csharp
internal class FhirJsonSerializerDataContractResolver : ISerializerDataContractResolver
{
    private readonly JsonSerializerOptions serializerOptions = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
    private readonly JsonSerializerDataContractResolver inner = new JsonSerializerDataContractResolver(new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });
    private readonly bool rewritePolymorphicProperties;

    public FhirJsonSerializerDataContractResolver(bool rewritePolymorphicProperties)
    {
        this.rewritePolymorphicProperties = rewritePolymorphicProperties;
    }

    public DataContract GetDataContractForType(Type type)
    {
        if (type == typeof(Time))
        {
            return DataContract.ForPrimitive(type, DataType.String, "time");
        }
        else if (type == typeof(FhirDateTime))
        {
            return DataContract.ForPrimitive(type, DataType.String, "date-time");
        }
        else if (type == typeof(FhirBoolean))
        {
            return DataContract.ForPrimitive(type, DataType.Boolean, null);
        }
        else if (type == typeof(Integer))
        {
            return DataContract.ForPrimitive(type, DataType.Integer, "int32");
        }
        else if (type == typeof(Integer64))
        {
            return DataContract.ForPrimitive(type, DataType.Integer, "int64");
        }
        else if (type == typeof(Uuid))
        {
            return DataContract.ForPrimitive(type, DataType.String, "uuid");
        }
        else if (type == typeof(FhirUri))
        {
            return DataContract.ForPrimitive(type, DataType.String, "uri");
        }
        else if (type == typeof(PositiveInt))
        {
            return DataContract.ForPrimitive(type, DataType.Number, null);
        }
        else if (type == typeof(UnsignedInt))
        {
            return DataContract.ForPrimitive(type, DataType.Number, null);
        }
        else if (type == typeof(Date))
        {
            return DataContract.ForPrimitive(type, DataType.String, "date");
        }
        else if (type == typeof(Base64Binary))
        {
            return DataContract.ForPrimitive(type, DataType.String, "byte");
        }
        else if (type == typeof(Hl7.Fhir.Model.DataType))
        {
            return DataContract.ForPrimitive(type, DataType.String, "dynamic");
        }
        else if (typeof(Base).IsAssignableFrom(type))
        {
            return DataContract.ForObject(type, GetDataPropertiesFor(type), null, null, null, JsonConverterFunc);
        }
        else if (type.IsEnum)
        {
            return DataContract.ForPrimitive(type, DataType.String, null, Enum.GetValues(type).Cast<object>().Select(v => EnumUtility.GetLiteral((Enum)v)));
        }
        else
        {
            return inner.GetDataContractForType(type);
        }
    }

    private string JsonConverterFunc(object value)
    {
        return JsonSerializer.Serialize(value, serializerOptions);
    }

    private IEnumerable<DataProperty> GetDataPropertiesFor(Type objectType)
    {
        IEnumerable<PropertyInfo> source;
        if (!objectType.IsInterface)
        {
            IEnumerable<PropertyInfo> properties = objectType.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
            source = properties;
        }
        else
        {
            source = new Type[1] { objectType }.Concat(objectType.GetInterfaces()).SelectMany((Type i) => i.GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic));
        }

        var isDomainResource = typeof(DomainResource).IsAssignableFrom(objectType);

        IOrderedEnumerable<PropertyInfo> orderedEnumerable = from property in source
                                                                orderby property.DeclaringType.GetInheritanceChain().Length
                                                                select property;
        List<DataProperty> dataProperties = new List<DataProperty>();
        foreach (PropertyInfo propertyInfo in orderedEnumerable)
        {
            if (!isDomainResource && propertyInfo.Name == "Extension")
            {
                continue;
            }

            string name = propertyInfo.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name ?? serializerOptions.PropertyNamingPolicy?.ConvertName(propertyInfo.Name) ?? propertyInfo.Name;

            if (rewritePolymorphicProperties && propertyInfo.PropertyType == typeof(Hl7.Fhir.Model.DataType))
            {
                dataProperties.Add(new DataProperty($"{name}[x]", isNullable: propertyInfo.PropertyType.IsReferenceOrNullableType(), isReadOnly: false, isWriteOnly: false, memberType: propertyInfo.PropertyType, isRequired: false, memberInfo: propertyInfo));
                var allowedTypes = propertyInfo.GetAttribute<Hl7.Fhir.Validation.AllowedTypesAttribute>()?.Types;

                if (allowedTypes != null)
                {
                    foreach (var allowedType in allowedTypes)
                    {
                        var fhirTypeName = allowedType.GetCustomAttribute<FhirTypeAttribute>()?.Name ?? allowedType.Name;
                        var actualType = allowedType.GetValueType();
                        dataProperties.Add(new DataProperty($"{name}{System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(fhirTypeName)}", isNullable: propertyInfo.PropertyType.IsReferenceOrNullableType(), isReadOnly: false, isWriteOnly: false, memberType: actualType, isRequired: false, memberInfo: propertyInfo));
                    }
                }
            }
            else
            {
                dataProperties.Add(new DataProperty(name, isNullable: propertyInfo.PropertyType.IsReferenceOrNullableType(), isReadOnly: false, isWriteOnly: false, memberType: propertyInfo.PropertyType, isRequired: false, memberInfo: propertyInfo));
            }
        }

        return dataProperties;
    }
}
```

**Comment by brianpos** [comment] 2022-06-14 23:50
Thanks, I'll take a look and see if we can shape this into something that makes sense to include.

**Comment by taylor-white-zocdoc** [comment] 2022-07-22 02:25
Thanks @almostchristian this is glorious.
